<?= '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <?php foreach($pages as $page): ?>
        
        <url>
            <loc><?= hs($page->page) ?></loc>
            <lastmod><?= date('Y-m-d', strtotime($page->updated)) ?></lastmod>
            <changefreq><?= hs($page->changefreq) ?></changefreq>
            <priority><?= hs($page->priority) ?></priority>
        </url>

    <?php endforeach; ?>

</urlset>